### ISSUE TITLE
Most used Tag-Cloud wieder aktivieren

### ISSUE THREAD

**Issue by wellemut** [kartevonmorgen/Glossaryofchange#5]
Die API unter https://api.ofdb.io/v0/entries/most-popular-tags?offset=0&limit=1000&min_count=100 funktioniert wieder. 

Service kann wieder aktiviert werden: https://glossardeswandels.de/tagcloud_kvm.php

**Comment by wellemut** [comment]
Danke @uklotzde fürs fixen der API!

**Comment by earthfriend** [comment]
Die Tagcloud ist jetzt wieder aktiv.
Es tauchen jetzt aber 2 spezielle Tags auf, die irgendwie automatisch für die Einträge vergeben werden: #commercial und #non-profit. Wofür sind die gedacht? Soll damit die Item-Category abgelöst werden? Jedenfalls werden mit #commercial jetzt offenbar alle Einträge gefunden.
Ich könnte die 2 Tags auch erstmal aus der Cloud herausfiltern.

**Comment by uklotzde** [comment]
Die Kategorien werden intern auf die Tags #commercial und #non-profit abgebildet, die jetzt zusätzlich sichtbar sind. Irgendwann werden die Kategorien auch aus der API komplett entfernt werden. Für die Tag Cloud macht es vermutlich Sinn, diese beiden speziellen Tags zu ignorieren.

**Comment by earthfriend** [comment]
Ok, ich überspringe die beiden Spezial-Tags jetzt einfach. Perspektivisch könnten wir dann ja noch die Gesamtanzahl von Initiativen und Unternehmen separat mit auf der Seite anzeigen.

**Comment by wellemut** [comment]
Ja genau richtig! Kannst du am besten ignorieren. Genau, dass ist eine neue Art, die Kathegorien zu spezifizieren. Dadurch kann jetzt uach ein Eintrag beide Attribute haben, in dem du manuell diesen Hashtag hinzufügst.

**Comment by wellemut** [comment]
Kannst du sogar bestimmte sprachen raus filtern?
Mit den Russischen worten kann ja im deutschen Glossar niemand was anfangen: экология

Perspektivisch sollten wir das natürich im Backend integrieren, dass dort Sprachen übersetzt werden und stichworte nur in der geünschten sprache gezeigt werden.

Aber wenn es da einen quicfix gäbe, wäre natürlich auch cool.

**Comment by earthfriend** [comment]
Ja, kein Problem. Ich lasse einfach alle Tags weg, die nicht den Latin1-Zeichensatz verwenden.
Es gibt noch ein paar Tags, die mit einem Bindestrich anfangen. Sind das fehlerhafte Einträge?

**Comment by uklotzde** [comment]
Vermutlich. Leider werden die Tags vom Backend nur unzureichend validiert und normalisiert. Erst wenn das mal implementiert sein sollte, macht eine finale manuelle/automatische Bereinigung der Datenbank Sinn.

**Comment by uklotzde** [comment]
https://github.com/kartevonmorgen/openfairdb/issues/206
https://github.com/kartevonmorgen/openfairdb/issues/175
https://github.com/kartevonmorgen/openfairdb/issues/39
https://github.com/kartevonmorgen/openfairdb/issues/188

**Comment by wellemut** [comment]
Vielen Dank!
