### ISSUE TITLE
Eintragszähler für jede Begriffsseite

### ISSUE THREAD

**Issue by wellemut** [kartevonmorgen/Glossaryofchange#6]
Das Glossar-Frontend kann schon einige Sachen, die auf der Karte von morgen noch Fehlen.
Z.B. die Anzahl der Suchergebnisse zeigen: https://github.com/kartevonmorgen/kartevonmorgen/issues/459

### Funktion
Könntest du über jeder Karte die "Anzahl Einträge mit Stichwort" einblenden, wie es schon bei der Tag-Cloud funktioniert? 
![grafik](https://user-images.githubusercontent.com/15019030/73924533-f047ff80-48cc-11ea-8d5f-42003e28e1e9.png)

### Design:
Das könnte direkt über der Karte, also noch unter den auswählbaren Begriffen "Suche mit Stichwort: " stehen.

Noch besser, schreib es doch vor das Zoom-level:
![grafik](https://user-images.githubusercontent.com/15019030/73925416-508b7100-48ce-11ea-987a-956ce26dbf97.png)

**Comment by earthfriend** [comment]
Ja, sowas in der Art werde ich mal probieren: wenn ein Stichwort angeklickt wird, dann die API nach dem Count befragen und den dann mit einblenden.

# Update:
Das Einblenden der Anzahl der Einträge habe ich jetzt mal als Beta-Version umgesetzt:
https://glossardeswandels.de/beta/#/?term=Gemeinschaftsgarten
 
Problematisch ist jedoch, dass die API bisher ja nur eine Liste liefert, oder kann man da schon ein bestimmtes Tag vorgeben?
Und durch die Begrenzung auf 1000 Tags gibt es kein Ergebnis für Tags mit Anzahl < 8.
Ich frage jetzt die API einmal beim Laden der Seite ab und cache das Ergebnis im Browser. Das bedeutet aber auch, wenn man einen Eintrag hinzufügt, dann erhöht sich die angezeigte Anzahl für ein verwendetes Tag erst wenn man die Seite komplett neu lädt.

**Comment by earthfriend** [comment]
Das Anzeigen der Anzahl ist jetzt auf der Hauptseite online.
